# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-05-21 18:02
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('checkList', '0002_remove_item_tick'),
    ]

    operations = [
        migrations.AlterField(
            model_name='item',
            name='info',
            field=models.TextField(default=b''),
        ),
    ]
