# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-05-21 22:31
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('checkList', '0003_auto_20170521_2332'),
    ]

    operations = [
        migrations.AddField(
            model_name='item',
            name='tick',
            field=models.BooleanField(default=False),
        ),
    ]
